/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PersonalSong {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'owner' : Principal,
  'audioFile' : ExternalBlob,
  'coverImage' : [] | [ExternalBlob],
  'artist' : string,
}
export interface Song {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'audioFile' : ExternalBlob,
  'coverImage' : [] | [ExternalBlob],
  'artist' : string,
}
export interface SongMetadata {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'coverImage' : [] | [ExternalBlob],
  'artist' : string,
}
export interface Update {
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'audioFile' : ExternalBlob,
  'coverImage' : [] | [ExternalBlob],
  'artist' : string,
}
export interface UserProfile {
  'hasActiveSubscription' : boolean,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'downloadPersonalSongAudio' : ActorMethod<[bigint], ExternalBlob>,
  'downloadSongAudio' : ActorMethod<[bigint], ExternalBlob>,
  'editPersonalSong' : ActorMethod<[bigint, Update], undefined>,
  'editSong' : ActorMethod<[bigint, Update], undefined>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPersonalSongMetadata' : ActorMethod<[], Array<SongMetadata>>,
  'getPersonalSongs' : ActorMethod<[], Array<PersonalSong>>,
  'getSong' : ActorMethod<[bigint], [] | [Song]>,
  'getSongsByDuration' : ActorMethod<[], Array<Song>>,
  'getTotalSongs' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPersonalSongOwner' : ActorMethod<[bigint], boolean>,
  'removePersonalSong' : ActorMethod<[bigint], undefined>,
  'removeSong' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'streamPersonalSongAudio' : ActorMethod<[bigint], ExternalBlob>,
  'streamSongAudio' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'uploadPersonalSong' : ActorMethod<[Update], bigint>,
  'uploadPublicSong' : ActorMethod<[Update], bigint>,
  'uploadSong' : ActorMethod<[Update], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];