/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Update = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'audioFile' : ExternalBlob,
  'coverImage' : IDL.Opt(ExternalBlob),
  'artist' : IDL.Text,
});
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'audioFile' : ExternalBlob,
  'coverImage' : IDL.Opt(ExternalBlob),
  'artist' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'hasActiveSubscription' : IDL.Bool,
  'name' : IDL.Text,
});
export const SongMetadata = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'artist' : IDL.Text,
});
export const PersonalSong = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'owner' : IDL.Principal,
  'audioFile' : ExternalBlob,
  'coverImage' : IDL.Opt(ExternalBlob),
  'artist' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'downloadPersonalSongAudio' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
  'downloadSongAudio' : IDL.Func([IDL.Nat], [ExternalBlob], []),
  'editPersonalSong' : IDL.Func([IDL.Nat, Update], [], []),
  'editSong' : IDL.Func([IDL.Nat, Update], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPersonalSongMetadata' : IDL.Func([], [IDL.Vec(SongMetadata)], ['query']),
  'getPersonalSongs' : IDL.Func([], [IDL.Vec(PersonalSong)], ['query']),
  'getSong' : IDL.Func([IDL.Nat], [IDL.Opt(Song)], ['query']),
  'getSongsByDuration' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getTotalSongs' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPersonalSongOwner' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'removePersonalSong' : IDL.Func([IDL.Nat], [], []),
  'removeSong' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'streamPersonalSongAudio' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
  'streamSongAudio' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'uploadPersonalSong' : IDL.Func([Update], [IDL.Nat], []),
  'uploadPublicSong' : IDL.Func([Update], [IDL.Nat], []),
  'uploadSong' : IDL.Func([Update], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Update = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'audioFile' : ExternalBlob,
    'coverImage' : IDL.Opt(ExternalBlob),
    'artist' : IDL.Text,
  });
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'audioFile' : ExternalBlob,
    'coverImage' : IDL.Opt(ExternalBlob),
    'artist' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'hasActiveSubscription' : IDL.Bool,
    'name' : IDL.Text,
  });
  const SongMetadata = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'artist' : IDL.Text,
  });
  const PersonalSong = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'owner' : IDL.Principal,
    'audioFile' : ExternalBlob,
    'coverImage' : IDL.Opt(ExternalBlob),
    'artist' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'downloadPersonalSongAudio' : IDL.Func(
        [IDL.Nat],
        [ExternalBlob],
        ['query'],
      ),
    'downloadSongAudio' : IDL.Func([IDL.Nat], [ExternalBlob], []),
    'editPersonalSong' : IDL.Func([IDL.Nat, Update], [], []),
    'editSong' : IDL.Func([IDL.Nat, Update], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPersonalSongMetadata' : IDL.Func(
        [],
        [IDL.Vec(SongMetadata)],
        ['query'],
      ),
    'getPersonalSongs' : IDL.Func([], [IDL.Vec(PersonalSong)], ['query']),
    'getSong' : IDL.Func([IDL.Nat], [IDL.Opt(Song)], ['query']),
    'getSongsByDuration' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getTotalSongs' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPersonalSongOwner' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'removePersonalSong' : IDL.Func([IDL.Nat], [], []),
    'removeSong' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'streamPersonalSongAudio' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
    'streamSongAudio' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'uploadPersonalSong' : IDL.Func([Update], [IDL.Nat], []),
    'uploadPublicSong' : IDL.Func([Update], [IDL.Nat], []),
    'uploadSong' : IDL.Func([Update], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };